{% set version = "0.4.1" %}
{% set name = "quantized-mesh-encoder" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e1f3ccd7360762eaa3ca6ac208899df31fefb3f410113327b3d0b33469e2899

build:
  number: 1
  skip: true  # [py<36] [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - cython
    - pip
  run:
    - python
    - attrs
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - quantized_mesh_encoder

about:
  home: https://github.com/kylebarron/quantized-mesh-encoder
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fast Python Quantized Mesh encoder
  description: |
    A fast Python Quantized Mesh encoder. Encodes a mesh with 100k coordinates and 180k triangles in 20ms.
  doc_url: https://github.com/kylebarron/quantized-mesh-encoder
  dev_url: https://github.com/kylebarron/quantized-mesh-encoder

extra:
  recipe-maintainers:
    - davidbrochart
    - kylebarron
