{% set version = "0.4.3" %}
{% set name = "quantized-mesh-encoder" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00be53849a3bae3e23d2e1bd6e6fe138b751e077f05ff3bea2f00d982ad82a9a

build:
  number: 2
  skip: true  # [py<36] [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - numpy
    - cython
    - pip
  run:
    - python
    - attrs

test:
  imports:
    - quantized_mesh_encoder

about:
  home: https://github.com/kylebarron/quantized-mesh-encoder
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fast Python Quantized Mesh encoder
  description: |
    A fast Python Quantized Mesh encoder. Encodes a mesh with 100k coordinates and 180k triangles in 20ms.
  doc_url: https://github.com/kylebarron/quantized-mesh-encoder
  dev_url: https://github.com/kylebarron/quantized-mesh-encoder

extra:
  recipe-maintainers:
    - davidbrochart
    - kylebarron
